name: Protected Deployment

on:
  workflow_dispatch:

jobs:

  staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Deploy staging
        run: echo "Deploying to staging"


  production:
    needs: staging
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy production
        run: echo "Deploying to production"